### PR TITLE
Disable DOCKER_BUILDKIT

### LINKED ISSUE #131: build stages not being pushed
We've been using v5 in a Github Action successfully for many months and it suddenly stopped pushing the build stages to ECR correctly, always only pushing the last stage with tag "1". I'm not aware of any relevant change on our side. The only thing I noticed is a more recent Github Actions runner version being used. Updating to docker-build-with-cache-action v6 didn't help.

I did a little digging and I think this is what's happening:

Apparently in your docker-build.sh the piping of the output in this code no longer works:
```
docker build \
    $cache_from \
    --tag "$DUMMY_IMAGE_NAME" \
    --file "${INPUT_CONTEXT}"/"${INPUT_DOCKERFILE}" \
    ${INPUT_BUILD_EXTRA_ARGS} \
    "${extra_args[@]}" \
    "${INPUT_CONTEXT}" | tee "$BUILD_LOG"
```

The build-output.log remains empty and _get_stages doesn't find any stages, so none get pushed, which in turn messes up our whole deployment.

Anyway, [sources on the internet](https://forums.docker.com/t/capture-ouput-of-docker-build-into-a-log-file/123178) say docker build no longer logs to standard output but rather to the standard error stream, so adding 2>&1 before the pipe operator should fix the problem. It does when I try to write docker build output to both the console and a file locally:

```
docker build . | tee test.log
```
--> full output in console, empty test.log

```
docker build . 2>&1 | tee test.log
```
--> full output in both console and test.log

### PR DESCRIPTION
**Pull request by whoan**
Closes #131

### CODE REVIEW

**Comment by ajaest** [comment]
With this change you have unadvertly broken all our builds in our company, relying in buildkit. I think using buildkit is legit (and needed to use things like "--mount").

**Comment by whoan** [comment]
@ajaest I am sorry to read that. To avoid that in the future, you should always stick to a specific version. eg: **v6.0.0**.

`DOCKER_BUILDKIT` had actually broken this action as the action relies on the old `docker build` output to do its job. With `DOCKER_BUILDKIT` enabled, it just rebuilds every time. 

If time allows it, I will look for ways to make this action to work even with `DOCKER_BUILDKIT` enabled, but for the moment, you can just use a previous version of the action, but again, with `DOCKER_BUILDKIT` enabled, it just rebuilds again.

**Comment by milandufek** [comment]
Moreover the fix cannot be changed even from ENV variable because the script always override the settings. There would be much more better to put something like that.

`export DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-0}`

To allow users to enable it if they want but keep it disabled by default.

**Comment by whoan** [comment]
I am aware of your concerns guys. I will do my best to fix the action for you. Just patience that I am doing this in my free time just for love.
Anyways, AFAIK, if you enable `DOCKER_BUILDKIT` again, the action will just build but without using the cache, which was the main purpose for it.
Regards.

**Comment by whoan** [comment]
FYI tip of v4, v5, v6, and v7 allow to set `DOCKER_BUILDKIT` variable. By default, it's `DOCKER_BUILDKIT=0`.

I plan to eventually default to `DOCKER_BUILDKIT=1`. See issue #138 for more information.

**Comment by ajaest** [comment]
Thanks @whoan, as you suggested I pinned version to v5.11.3 and now it is working again. It is true that caching is not working with DOCKER_BUILDKIT=1, but we didn't realize. Anyways, at least the build works and we are not in a hurry.

**Pull request merged**
