### PR TITLE
Add exit code for failed $INPUT_PUSH_IMAGE_AND_STAGES

### PR DESCRIPTION
**Pull request by NullableInt**
My builds are green even when this part fails. Making me think I did a good job, but when I look at the logs I can see that it failed. This is just a suggestion though.

### CODE REVIEW

**Comment by whoan** [comment]
Good catch @NullableInt . I still think that if the user sets `false`, it wouldn't fail, as he/she expects not to push.

Something like this would be better IMO:

    if ! $INPUT_PUSH_IMAGE_AND_STAGES; then
      echo "Not pushing" >&2
      [ $INPUT_PUSH_IMAGE_AND_STAGES = false ]
      return
    fi

**Comment by NullableInt** [comment]
I agree! That looks a lot better!

**Comment by whoan** [comment]
Thanks @NullableInt

**Comment by NullableInt** [comment]
I now get a failed build and the error message for what went wrong :pray:
Thank you for merging this!

**Pull request merged**
