### PR TITLE
ShellCheck fixes

### PR DESCRIPTION
**Pull request by asbjornu**
This PR fixes the minor issues pointed out by ShellCheck (as added in #45). Since this builds on #45, that PR can be merged first and when it is, I'll rebase this PR.

### CODE REVIEW

**Comment by asbjornu** [comment]
This is now rebased after the merge of #45.

I'm not sure why [`docker build` failed](https://github.com/whoan/docker-build-with-cache-action/pull/46/checks?check_run_id=699537821#step:3:114) with `"docker build" requires exactly 1 argument` just now and I'm unsure about eea8e1300ecffebcbf434ab546f0353714b698d1, since `INPUT_IMAGE_NAME` is used as an array, just not in the very instance ShellCheck complains about.

Thoughts, @whoan?

**Comment by whoan** [comment]
@asbjornu `$INPUT_BUILD_EXTRA_ARGS` shouldn't be quoted to allow word splitting (to nothing in this case). I will check this further later today.

**Comment by asbjornu** [comment]
I added `# shellcheck disable=SC2086` to `$INPUT_BUILD_EXTRA_ARGS`, but there's still a problem with `docker build`. There's probably more `# shellcheck disable=SC2086` to be added, I guess.

**Comment by whoan** [comment]
@asbjornu The problem is that you can't add comments in the middle of a multi line command

**Comment by asbjornu** [comment]
Ah of course. 🤦 Fixed that. Now I think it should all work and the reason it due to `secrets.GITHUB_TOKEN` not being available for pull requests. It would be good to do everything up until `docker push` also for pull requests. Ideas on how to accomplish that?

**Comment by whoan** [comment]
There should be two workflows; one triggered by `push` event, which will have right to (docker) `push`, and another triggered by `pull_request` whit `push_image_and_stages: false` to avoid pushing.

**Comment by asbjornu** [comment]
🎉

**Pull request merged**
