### PR TITLE
Fix BUILD_EXTRA_ARGS json input

### LINKED ISSUE #91: Unable to pass in a multiline string in build arg
This config does not work:

`build_extra_args: --build-arg some_arg="$multiline_string"`

For

```
multiline_string='----first line of text----
middle lines of text
----last line of text----'
```

I get an error like:

```
docker build --tag my_awesome_image --file ./Dockerfile --target release --build-arg 'some_arg="----first' line of text---- *** middle lines of text ----last line of 'text----"' .
bad flag syntax: ----last
See 'docker build --help'.
```

However, this *does* work if I run the equivalent docker build command using the cli.

### PR DESCRIPTION
**Pull request by whoan**
Test: https://github.com/whoan/hello-world/runs/1947026731

Could you please check this @bob-bins

Close #91

### CODE REVIEW

**Comment by bob-bins** [comment]
Hello! I am still getting the `Load key "/root/.ssh/id_rsa": invalid format` error when using `whoan/docker-build-with-cache-action@fix-json-extra-args`

**Comment by whoan** [comment]
Ok @bob-bins . I assume the `target` is parsed correctly now.

Regarding the "Load key" error, I can't figure out how it is related to the action. From what I see, you are using `ssh_key=<key>` not `ssh_key=<path to key>` so I wonder if the error is somewhere else.

I might be missing something, so please help me to understand the error. If you can share the whole action output, that would be helpful.

Thanks

**Comment by bob-bins** [comment]
The "load key" error is happening because the `ssh_key` that ultimately is passed into `docker build` is an invalid format when I try to use it for downloading a private github package. If I pass in the ssh key through plain bash `--build-arg ssh_key="$ssh_key"` I don't get the error, which indicates there may be a problem with it getting parsed from a single-line string with `\n` back into a multiline string before getting passed into `docker build --build-arg` within the github action.

I'll see if I can figure out exactly what's happening with a fake key.

**Comment by bob-bins** [comment]
found so far that having both `--target` and `--build-arg` in `build_extra_args` causes at least the `--build-arg` to be ignored, if not both of them.

**Comment by whoan** [comment]
@bob-bins That is interesting. I the test I run in hello-world project, I see both argument being parsed correctly:

     + docker build --cache-from=whoan/hello-world-stages:1 --cache-from=whoan/hello-world-stages:2 --cache-from=whoan/hello-world-stages:3 --cache-from=whoan/hello-world-stages:4 --cache-from=whoan/hello-world-stages:5 --tag my_awesome_image --file ./Dockerfile --build-arg 'myarg=hola
    mundo' --target one-target .

**Pull request merged**
